# Generated by Django 5.1 on 2025-12-25 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("financial_account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "color",
                    models.CharField(blank=True, help_text="Hex color code", max_length=7),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                            ("investment", "Investment"),
                            ("other", "Other"),
                        ],
                        default="expense",
                        help_text="Category type determines transaction classification",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="transaction.transactioncategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transaction_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Transaction date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive)",
                        max_digits=15,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        default="debit",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("posted", "Posted"),
                            ("reconciled", "Reconciled"),
                        ],
                        default="posted",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "sync_source",
                    models.CharField(
                        choices=[
                            ("plaid", "Plaid"),
                            ("manual", "Manual Entry"),
                            ("csv", "CSV Import"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External ID from sync source (e.g., Plaid transaction ID)",
                        max_length=255,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw transaction data from external source",
                        null=True,
                    ),
                ),
                (
                    "categorization_status",
                    models.CharField(
                        choices=[
                            ("uncategorized", "Uncategorized"),
                            ("pending_ai", "Pending AI Categorization"),
                            ("categorized", "Categorized"),
                        ],
                        default="uncategorized",
                        help_text="Status of categorization for this transaction",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes for this transaction",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="financial_account.financialaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transaction.transactioncategory",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategoryKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="Case-insensitive keyword for matching",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match_count",
                    models.IntegerField(default=0, help_text="Number of times this keyword has matched"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_keywords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="transaction.transactioncategory",
                    ),
                ),
            ],
            options={
                "db_table": "category_keyword",
                "ordering": ["-match_count", "keyword"],
            },
        ),
        migrations.CreateModel(
            name="RecategorizationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_count", models.IntegerField(default=0)),
                ("processed_count", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("keep_existing_for_unmatched", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recategorization_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recategorization_task",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-started_at"],
                        name="recategoriz_user_id_c5b11c_idx",
                    ),
                    models.Index(fields=["status"], name="recategoriz_status_b7b825_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="transactioncategory",
            index=models.Index(fields=["user", "slug"], name="transaction_user_id_686c95_idx"),
        ),
        migrations.AddIndex(
            model_name="transactioncategory",
            index=models.Index(fields=["parent"], name="transaction_parent__163bef_idx"),
        ),
        migrations.AddIndex(
            model_name="transactioncategory",
            index=models.Index(fields=["type"], name="transaction_type_08e37d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="transactioncategory",
            unique_together={("slug", "user")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user", "-date"], name="transaction_user_id_0f2f78_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["account", "-date"], name="transaction_account_ead58b_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["category"], name="transaction_categor_c453c0_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["external_id"], name="transaction_externa_407619_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["sync_source"], name="transaction_sync_so_0430f8_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["categorization_status"], name="transaction_categor_f95f02_idx"),
        ),
        migrations.AddIndex(
            model_name="categorykeyword",
            index=models.Index(fields=["keyword"], name="category_ke_keyword_7b3577_idx"),
        ),
        migrations.AddIndex(
            model_name="categorykeyword",
            index=models.Index(fields=["category"], name="category_ke_categor_28ac2c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="categorykeyword",
            unique_together={("category", "keyword")},
        ),
    ]
