# Generated by Django 4.2.24 on 2025-12-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="categorization_status",
            field=models.CharField(
                choices=[
                    ("uncategorized", "Uncategorized"),
                    ("pending_ai", "Pending AI Categorization"),
                    ("categorized", "Categorized"),
                ],
                default="uncategorized",
                help_text="Status of categorization for this transaction",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["categorization_status"], name="transaction_categor_f95f02_idx"
            ),
        ),
    ]
