# Generated by Django 5.1 on 2025-12-13 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notes for this transaction",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="KeywordRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="Case-insensitive substring", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_rules",
                        to="transaction.transactioncategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transaction_keyword_rule",
                "indexes": [
                    models.Index(
                        fields=["user", "keyword"],
                        name="transaction_user_id_69dc42_idx",
                    )
                ],
                "unique_together": {("user", "keyword")},
            },
        ),
    ]
