# Generated by Django 5.1 on 2025-12-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_redesign_categorization"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="keywordrule",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="keywordrule",
            name="category",
        ),
        migrations.RemoveField(
            model_name="keywordrule",
            name="user",
        ),
        migrations.RenameIndex(
            model_name="categorykeyword",
            new_name="category_ke_keyword_7b3577_idx",
            old_name="category_kw_keyword_idx",
        ),
        migrations.RenameIndex(
            model_name="categorykeyword",
            new_name="category_ke_categor_28ac2c_idx",
            old_name="category_kw_category_idx",
        ),
        migrations.RenameIndex(
            model_name="transactioncategory",
            new_name="transaction_type_08e37d_idx",
            old_name="transaction_type_idx",
        ),
        migrations.DeleteModel(
            name="KeywordRule",
        ),
    ]
