# Generated by Django 5.1 on 2025-12-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0005_remove_merchant_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_merchan_7a0b93_idx",
        ),
        migrations.RemoveField(
            model_name="transactioncategory",
            name="is_expense",
        ),
        migrations.RemoveField(
            model_name="transactioncategory",
            name="is_income",
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("transfer", "Transfer"),
                    ("investment", "Investment"),
                ],
                default="expense",
                help_text="Category type determines transaction classification",
                max_length=20,
            ),
        ),
    ]
