# Generated by Django 4.2.24 on 2025-12-14 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0007_categorykeyword_user_alter_transactioncategory_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioncategory",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("transfer", "Transfer"),
                    ("investment", "Investment"),
                    ("other", "Other"),
                ],
                default="expense",
                help_text="Category type determines transaction classification",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecategorizationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_count", models.IntegerField(default=0)),
                ("processed_count", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("keep_existing_for_unmatched", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recategorization_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recategorization_task",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-started_at"],
                        name="recategoriz_user_id_c5b11c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="recategoriz_status_b7b825_idx"
                    ),
                ],
            },
        ),
    ]
