# Generated by Django 5.1 on 2025-12-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0008_alter_transactioncategory_type_recategorizationtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="External ID from sync source (e.g., Plaid transaction ID)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sync_source",
            field=models.CharField(
                choices=[
                    ("plaid", "Plaid"),
                    ("manual", "Manual Entry"),
                    ("csv", "CSV Import"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
