# Generated by Django 4.2.16 on 2025-03-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="google_sheets_link",
        ),
    ]
