# Generated by Django 4.2.16 on 2024-11-25 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0003_category_cardaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
