# Generated by Django 4.2.16 on 2024-11-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0004_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="default", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
