# Generated by Django 4.2.16 on 2024-11-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0005_remove_user_email_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="types",
            new_name="type",
        ),
    ]
