# Generated by Django 5.1.7 on 2025-04-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0006_remove_category_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cardaccount",
            old_name="credit_card_type",
            new_name="card_type",
        ),
    ]
