# Generated by Django 4.2.16 on 2024-12-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0006_rename_types_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="import_path",
            field=models.CharField(default="", max_length=100),
        ),
    ]
