# Generated by Django 4.2.16 on 2024-12-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0007_user_import_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="import_path",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
