# Generated by Django 5.1.7 on 2025-04-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0007_rename_credit_card_type_cardaccount_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("travel", "Travel"),
                    ("shopping", "Shopping"),
                    ("groceries", "Groceries"),
                    ("entertainment", "Entertainment"),
                    ("utilities", "Utilities"),
                    ("housing", "Housing"),
                    ("medical", "Medical"),
                    ("transportation", "Transportation"),
                    ("education", "Education"),
                    ("savings", "Savings"),
                    ("gifts", "Gifts"),
                    ("dining", "Dining"),
                    ("investments", "Investments"),
                    ("subscriptions", "Subscriptions"),
                    ("charity/donations", "Charity/Donations"),
                    ("pet", "Pet"),
                    ("fun", "Fun"),
                    ("costco", "Costco"),
                    ("car", "Car"),
                    ("miscellaneous", "Miscellaneous"),
                    ("phone", "Phone"),
                    ("internet", "Internet"),
                ],
                max_length=100,
            ),
        ),
    ]
