# Generated by Django 4.2.16 on 2024-12-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0008_alter_user_import_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_sheets_link",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
