# Generated by Django 5.1.7 on 2025-04-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0008_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("travel", "Travel"),
                    ("shopping", "Shopping"),
                    ("online_shopping", "Online Shopping"),
                    ("groceries", "Groceries"),
                    ("entertainment", "Entertainment"),
                    ("utilities", "Utilities"),
                    ("housing", "Housing"),
                    ("medical", "Medical"),
                    ("education", "Education"),
                    ("savings", "Savings"),
                    ("gifts", "Gifts"),
                    ("dining", "Dining"),
                    ("investments", "Investments"),
                    ("subscriptions", "Subscriptions"),
                    ("charity_donations", "Charity/Donations"),
                    ("pet", "Pet"),
                    ("costco", "Costco"),
                    ("car", "Car"),
                    ("phone", "Phone"),
                    ("miscellaneous", "Miscellaneous"),
                    ("payments", "Payments"),
                    ("unknown", "Unknown"),
                ],
                max_length=100,
            ),
        ),
    ]
