# Generated by Django 5.1.7 on 2025-04-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "richtato_user",
            "0011_remove_category_keywords_alter_category_budget_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardaccount",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("american_express", "American Express"),
                    ("bank_of_america", "Bank of America"),
                    ("bilt", "BILT"),
                    ("chase", "Chase"),
                    ("citibank", "Citibank"),
                ],
                max_length=50,
            ),
        ),
    ]
