# Generated by Django 5.2.1 on 2025-06-24 14:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0014_rename_card_bank_cardaccount_bank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("user", "name")},
        ),
        migrations.AlterField(
            model_name="cardaccount",
            name="bank",
            field=models.CharField(
                choices=[
                    ("american_express", "American Express"),
                    ("bank_of_america", "Bank of America"),
                    ("bilt", "BILT"),
                    ("chase", "Chase"),
                    ("citibank", "Citibank"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Travel", "Travel"),
                    ("Shopping", "Shopping"),
                    ("Online_Shopping", "Online Shopping"),
                    ("Groceries", "Groceries"),
                    ("Entertainment", "Entertainment"),
                    ("Utilities", "Utilities"),
                    ("Housing", "Housing"),
                    ("Medical", "Medical"),
                    ("Education", "Education"),
                    ("Savings", "Savings"),
                    ("Gifts", "Gifts"),
                    ("Dining", "Dining"),
                    ("Investments", "Investments"),
                    ("Subscriptions", "Subscriptions"),
                    ("Charity_Donations", "Charity/Donations"),
                    ("Pet", "Pet"),
                    ("Costco", "Costco"),
                    ("Car", "Car"),
                    ("Phone", "Phone"),
                    ("Miscellaneous", "Miscellaneous"),
                    ("Payments", "Payments"),
                    ("Unknown", "Unknown"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="category",
            name="budget",
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=10
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="richtato_user.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "category", "start_date")},
            },
        ),
    ]
