# Generated by Django 5.2.1 on 2025-07-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0018_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Travel", "Travel"),
                    ("Shopping", "Shopping"),
                    ("Online Shopping", "Online Shopping"),
                    ("Groceries", "Groceries"),
                    ("Entertainment", "Entertainment"),
                    ("Utilities", "Utilities"),
                    ("Housing", "Housing"),
                    ("Medical", "Medical"),
                    ("Education", "Education"),
                    ("Savings", "Savings"),
                    ("Gifts", "Gifts"),
                    ("Dining", "Dining"),
                    ("Investments", "Investments"),
                    ("Subscriptions", "Subscriptions"),
                    ("Charity", "Charity"),
                    ("Pet", "Pet"),
                    ("Wholesale", "Wholesale"),
                    ("Car", "Car"),
                    ("Phone", "Phone"),
                    ("Miscellaneous", "Miscellaneous"),
                    ("Payments", "Payments"),
                ],
                max_length=100,
            ),
        ),
    ]
