# Generated by Django 5.2.3 on 2025-07-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0019_user_email_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="demo_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
