# Generated by Django 4.2.24 on 2025-12-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teller", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tellerconnection",
            new_name="teller_conn_user_id_851d30_idx",
            old_name="teller_conn_user_id_87c5a9_idx",
        ),
        migrations.RenameIndex(
            model_name="tellerconnection",
            new_name="teller_conn_teller__b7774c_idx",
            old_name="teller_conn_teller__6f4e1c_idx",
        ),
        migrations.AddField(
            model_name="tellerconnection",
            name="initial_backfill_complete",
            field=models.BooleanField(
                default=False,
                help_text="Whether the initial historical transaction backfill has been completed",
            ),
        ),
        migrations.AddField(
            model_name="tellerconnection",
            name="oldest_transaction_date",
            field=models.DateField(
                blank=True, help_text="Date of the oldest transaction synced", null=True
            ),
        ),
    ]
