# Generated by Django 5.1.7 on 2025-04-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0003_alter_expense_date_alter_expense_id"),
        ("richtato_user", "0007_rename_credit_card_type_cardaccount_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="richtato_user.category",
            ),
        ),
    ]
