# Generated by Django 5.1.7 on 2025-04-03 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0004_alter_expense_category"),
        ("richtato_user", "0013_rename_card_type_cardaccount_card_bank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.UniqueConstraint(
                fields=("date", "description", "amount", "account_name"),
                name="unique_expense",
            ),
        ),
    ]
