# Generated by Django 5.1.7 on 2025-04-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0005_expense_unique_expense"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="expense",
            name="unique_expense",
        ),
    ]
