# Generated by Django 5.1 on 2026-05-23 05:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("financial_account", "0011_statementfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "login_id",
                    models.CharField(
                        help_text="Stable identifier for this bank login as known to the extension. Used so re-captures from the same login overwrite the existing connection instead of creating a duplicate.",
                        max_length=120,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User-facing label, e.g. 'Bank of America (Personal)'.",
                        max_length=120,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("reauth_required", "Re-auth Required"),
                            ("disabled", "Disabled"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Only"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Every 2 Weeks"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=16,
                    ),
                ),
                (
                    "preferred_run_hour_local",
                    models.PositiveSmallIntegerField(
                        default=6, help_text="0-23. Hour of day to run the automation in the user's timezone."
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this connection is next eligible to run. NULL means manual-only.",
                        null=True,
                    ),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_failure_reason", models.TextField(blank=True, default="")),
                (
                    "next_reauth_estimated_at",
                    models.DateTimeField(
                        blank=True, help_text="Heuristic estimate of when the bank session will expire.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_connections",
                        to="financial_account.financialinstitution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bank_connection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankAutomationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "failure_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("session_expired", "Session Expired"),
                            ("dom_broken", "DOM Broken"),
                            ("no_download", "No Download"),
                            ("import_rejected", "Import Rejected"),
                            ("config", "Configuration Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("accounts_attempted", models.PositiveIntegerField(default=0)),
                ("accounts_succeeded", models.PositiveIntegerField(default=0)),
                ("statements_imported", models.PositiveIntegerField(default=0)),
                (
                    "triggered_by",
                    models.CharField(default="scheduler", help_text="scheduler | manual | extension", max_length=16),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="bank_automation.bankconnection",
                    ),
                ),
            ],
            options={
                "db_table": "bank_automation_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="BankAccountLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "flow",
                    models.CharField(
                        choices=[("deposit", "Deposit (Checking/Savings)"), ("credit_card", "Credit Card")],
                        default="deposit",
                        max_length=16,
                    ),
                ),
                (
                    "activity_url_encrypted",
                    models.TextField(
                        blank=True, default="", help_text="Encrypted activity URL including bank-specific tokens."
                    ),
                ),
                (
                    "external_account_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank-side opaque account token (e.g. BofA `adx`).",
                        max_length=255,
                    ),
                ),
                (
                    "detected_account_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Account name as seen on the bank site at capture time.",
                        max_length=255,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financial_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account_links",
                        to="financial_account.financialaccount",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_links",
                        to="bank_automation.bankconnection",
                    ),
                ),
            ],
            options={
                "db_table": "bank_account_link",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("storage_state_blob", models.TextField(help_text="Fernet-encrypted Playwright storage_state JSON.")),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at_estimated", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="bank_automation.bankconnection",
                    ),
                ),
            ],
            options={
                "db_table": "bank_session",
            },
        ),
        migrations.AddIndex(
            model_name="bankconnection",
            index=models.Index(fields=["user", "status"], name="bank_connec_user_id_12c433_idx"),
        ),
        migrations.AddIndex(
            model_name="bankconnection",
            index=models.Index(fields=["next_run_at"], name="bank_connec_next_ru_2a8d9b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="bankconnection",
            unique_together={("user", "institution", "login_id")},
        ),
        migrations.AddIndex(
            model_name="bankautomationrun",
            index=models.Index(fields=["connection", "-started_at"], name="bank_automa_connect_183330_idx"),
        ),
        migrations.AddIndex(
            model_name="bankautomationrun",
            index=models.Index(fields=["status"], name="bank_automa_status_1dda5a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="bankaccountlink",
            unique_together={("connection", "financial_account")},
        ),
    ]
