# Generated by Django 5.1 on 2026-05-23 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_automation", "0001_initial"),
        ("financial_account", "0011_statementfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccountlink",
            name="financial_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Richtato account this captured bank account maps to. May be NULL directly after a Chrome-extension capture if the user hasn't bound it yet — the runner will skip those until they do.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_account_links",
                to="financial_account.financialaccount",
            ),
        ),
    ]
