version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python richtato/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    networks:
      - backend

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3100:3100"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #     - GF_SECURITY_ADMIN_USER=admin
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   networks:
  #     - backend

# volumes:
#   grafana_data:  # Volume for Grafana data persistence

networks:
  backend:  # Isolated network for Django and Grafana communication