# Generated by Django 4.2.29 on 2026-04-13 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Household display name', max_length=100)),
                ('invite_code', models.CharField(blank=True, help_text='Single-use invite code for joining', max_length=32, null=True, unique=True)),
                ('invite_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='household.household')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'household_member',
            },
        ),
    ]
