[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "utilities"
version = "0.1.0"
description = "Richtato Utils"
authors = [
    { name = "brotatokuo", email = "kuoalan9@example.com" }
]
dependencies = [
]
