"""Render bank-agent setup payloads as YAML."""

from __future__ import annotations

import json
from typing import Any


def dump_bank_agent_setup_yaml(
    *,
    config: dict[str, Any],
    env: dict[str, str] | None = None,
) -> str:
    """Render a setup file with optional env credentials and login config."""
    lines = [
        "# Generated by Richtato — do not commit",
    ]
    if env:
        lines.append("env:")
        for key in ("RICHTATO_API_TOKEN", "BANK_AGENT_FERNET_KEY"):
            if env.get(key):
                lines.append(f"  {key}: {_quote(env[key])}")
        lines.append("")

    lines.extend(
        [
            f"version: {config['version']}",
            f"generated_at: {_quote(config['generated_at'])}",
            f"user_id: {config['user_id']}",
            f"source: {_quote(config['source'])}",
            "logins:",
        ]
    )
    for login in config["logins"]:
        lines.extend(
            [
                f"  - institution: {_quote(login['institution'])}",
                f"    nickname: {_quote(login['nickname'])}",
                f"    cadence: {_quote(login['cadence'])}",
                f"    hour: {login['hour']}",
                "    accounts:",
            ]
        )
        for account in login["accounts"]:
            lines.extend(
                [
                    f"      - name: {_quote(account['name'])}",
                    f"        flow: {_quote(account['flow'])}",
                    f"        storage_uri: {_quote(account['storage_uri'])}",
                    f"        richtato_account_id: {account['richtato_account_id']}",
                ]
            )
            if account.get("activity_url"):
                lines.append(f"        activity_url: {_quote(account['activity_url'])}")
    if not config["logins"]:
        lines.append("  []")
    return "\n".join(lines) + "\n"


def _quote(value: str) -> str:
    return json.dumps(value)
