# Generated by Cursor on 2026-05-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("source", models.CharField(default="system", max_length=64)),
                ("source_key", models.CharField(blank=True, default="", max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True, default="")),
                ("action_url", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_app_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inappnotification",
            index=models.Index(fields=["user", "read_at", "-created_at"], name="core_inappn_user_id_6e351f_idx"),
        ),
        migrations.AddIndex(
            model_name="inappnotification",
            index=models.Index(
                fields=["user", "source", "source_key", "-created_at"],
                name="core_inappn_user_id_dd2b4c_idx",
            ),
        ),
    ]
