[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graph"
version = "0.1.0"
description = "A graph package"
authors = [
    { name = "brotatokuo", email = "kuoalan9@example.com" }
]
dependencies = [
    "pandas>=2.0"
]
