# Generated by Django 5.1.7 on 2025-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
