# Generated by Django 5.1.7 on 2025-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0003_alter_income_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(default="1900-01-01"),
            preserve_default=False,
        ),
    ]
