# Generated by Django 5.1.7 on 2025-04-03 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_account_id_alter_accounttransaction_id"),
        ("income", "0004_alter_income_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="income",
            constraint=models.UniqueConstraint(
                fields=("date", "description", "amount", "account_name"),
                name="unique_income",
            ),
        ),
    ]
