# Generated by Django 5.1.7 on 2025-04-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0005_income_unique_income"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="income",
            name="unique_income",
        ),
    ]
