# Generated by Django 4.2.24 on 2025-12-03 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial_account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("teller", "Teller"),
                            ("plaid", "Plaid"),
                            ("manual", "Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        help_text="Encrypted access token for the provider",
                        max_length=500,
                    ),
                ),
                ("institution_name", models.CharField(max_length=255)),
                (
                    "external_account_id",
                    models.CharField(
                        help_text="Account ID in the external system", max_length=255
                    ),
                ),
                (
                    "external_enrollment_id",
                    models.CharField(
                        blank=True,
                        help_text="Enrollment/connection ID in external system",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                            ("pending", "Pending Setup"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Only"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("realtime", "Real-time"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "initial_backfill_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the initial historical transaction backfill has been completed",
                    ),
                ),
                (
                    "oldest_transaction_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the oldest transaction synced",
                        null=True,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="The financial account this connection syncs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_connections",
                        to="financial_account.financialaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sync_connection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("transactions_synced", models.IntegerField(default=0)),
                ("transactions_skipped", models.IntegerField(default=0)),
                ("batches_processed", models.IntegerField(default=0)),
                (
                    "is_full_sync",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this was a full historical sync",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        help_text="List of errors encountered during sync",
                        null=True,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="sync.syncconnection",
                    ),
                ),
            ],
            options={
                "db_table": "sync_job",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["connection", "-started_at"],
                        name="sync_job_connect_5f6d5f_idx",
                    ),
                    models.Index(fields=["status"], name="sync_job_status_b14182_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="syncconnection",
            index=models.Index(
                fields=["user", "status"], name="sync_connec_user_id_9df8b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncconnection",
            index=models.Index(
                fields=["provider", "external_account_id"],
                name="sync_connec_provide_912cee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncconnection",
            index=models.Index(
                fields=["account"], name="sync_connec_account_63f7d2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncconnection",
            unique_together={("provider", "external_account_id", "user")},
        ),
    ]
