# Generated by Django 5.1 on 2025-12-20 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_syncing", models.BooleanField(default=False)),
                ("last_sync_started", models.DateTimeField(blank=True, null=True)),
                ("last_sync_completed", models.DateTimeField(blank=True, null=True)),
                ("new_transaction_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Sync Status",
                "verbose_name_plural": "User Sync Statuses",
                "db_table": "user_sync_status",
            },
        ),
    ]
