# Generated by Django 5.1 on 2025-12-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_add_user_sync_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncconnection",
            name="newest_transaction_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the newest transaction synced (for incremental sync)",
                null=True,
            ),
        ),
    ]
