# Generated by Django 5.1 on 2025-12-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_add_newest_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncconnection",
            name="provider",
            field=models.CharField(
                choices=[("plaid", "Plaid"), ("manual", "Manual")], max_length=50
            ),
        ),
    ]
