# Generated by Django 4.2.18 on 2025-03-10 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('retirement', 'Retirement'), ('investment', 'Investment')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('latest_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('latest_balance_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='account.account')),
            ],
        ),
    ]
