# Generated by Django 4.2.16 on 2024-12-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounttransaction",
            options={},
        ),
        migrations.RenameField(
            model_name="accounttransaction",
            old_name="balance_history",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="accounttransaction",
            old_name="date_history",
            new_name="date",
        ),
        migrations.AddField(
            model_name="account",
            name="latest_balance_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
