# Generated by Django 4.2.16 on 2024-12-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_accounttransaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="latest_balance_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
