# Generated by Django 4.2.18 on 2025-03-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_bank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bank_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("checking", "Checking"),
                    ("savings", "Savings"),
                    ("retirement", "Retirement"),
                    ("investment", "Investment"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
