# Generated by Django 5.1.7 on 2025-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_account_bank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="accounttransaction",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
