# Generated by Django 5.1.7 on 2025-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_account_id_alter_accounttransaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="bank_name",
        ),
        migrations.AddField(
            model_name="account",
            name="asset_type_name",
            field=models.CharField(
                choices=[
                    ("bank_of_america", "Bank of America"),
                    ("chase", "Chase"),
                    ("citibank", "Citibank"),
                    ("marcus", "Marcus by Goldman Sachs"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
