# Generated by Django 5.1.7 on 2025-04-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_account_bank_name_account_asset_type_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="asset_type_name",
            new_name="asset_entity_name",
        ),
    ]
