# Generated by Django 5.1 on 2025-12-25 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.financial_account.migrations.0003_add_is_liability_field
# apps.financial_account.migrations.0004_seed_financial_institutions


def set_credit_cards_as_liability(apps, schema_editor):
    """Set is_liability=True for existing credit card accounts."""
    FinancialAccount = apps.get_model("financial_account", "FinancialAccount")
    FinancialAccount.objects.filter(account_type="credit_card").update(is_liability=True)


def reverse_credit_cards_liability(apps, schema_editor):
    """Reverse: set is_liability=False for all accounts."""
    FinancialAccount = apps.get_model("financial_account", "FinancialAccount")
    FinancialAccount.objects.filter(account_type="credit_card").update(is_liability=False)


COMMON_INSTITUTIONS = [
    # Major US Banks
    {"name": "Chase", "slug": "chase"},
    {"name": "Bank of America", "slug": "bank_of_america"},
    {"name": "Wells Fargo", "slug": "wells_fargo"},
    {"name": "Citibank", "slug": "citibank"},
    {"name": "Capital One", "slug": "capital_one"},
    {"name": "US Bank", "slug": "us_bank"},
    {"name": "PNC Bank", "slug": "pnc"},
    {"name": "TD Bank", "slug": "td_bank"},
    # Online Banks
    {"name": "Ally Bank", "slug": "ally"},
    {"name": "Discover Bank", "slug": "discover"},
    {"name": "SoFi", "slug": "sofi"},
    # Credit Card Issuers
    {"name": "American Express", "slug": "american_express"},
    # Investment / Brokerage
    {"name": "Marcus by Goldman Sachs", "slug": "marcus"},
    {"name": "Robinhood", "slug": "robinhood"},
    {"name": "Charles Schwab", "slug": "schwab"},
    {"name": "Fidelity", "slug": "fidelity"},
    {"name": "Vanguard", "slug": "vanguard"},
    # Credit Unions
    {"name": "Navy Federal Credit Union", "slug": "navy_federal"},
    # Other
    {"name": "Other", "slug": "other"},
]


def seed_institutions(apps, schema_editor):
    """Create common financial institutions."""
    FinancialInstitution = apps.get_model("financial_account", "FinancialInstitution")

    for inst_data in COMMON_INSTITUTIONS:
        FinancialInstitution.objects.get_or_create(slug=inst_data["slug"], defaults={"name": inst_data["name"]})


def reverse_seed(apps, schema_editor):
    """Remove seeded institutions (only if not linked to accounts)."""
    FinancialInstitution = apps.get_model("financial_account", "FinancialInstitution")

    slugs_to_remove = [inst["slug"] for inst in COMMON_INSTITUTIONS]
    # Only delete institutions that have no linked accounts
    FinancialInstitution.objects.filter(slug__in=slugs_to_remove, accounts__isnull=True).delete()


class Migration(migrations.Migration):
    replaces = [
        ("financial_account", "0001_initial"),
        ("financial_account", "0002_initial"),
        ("financial_account", "0003_add_is_liability_field"),
        ("financial_account", "0004_seed_financial_institutions"),
        ("financial_account", "0005_add_image_key_to_financial_account"),
        ("financial_account", "0006_make_account_number_last4_nullable"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("support_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "financial_institution",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Account nickname or name", max_length=255),
                ),
                (
                    "account_number_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of account number",
                        max_length=4,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking Account"),
                            ("savings", "Savings Account"),
                            ("credit_card", "Credit Card"),
                        ],
                        default="checking",
                        max_length=20,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current balance",
                        max_digits=15,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sync_source",
                    models.CharField(
                        choices=[
                            ("teller", "Teller"),
                            ("manual", "Manual Entry"),
                            ("csv", "CSV Import"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="financial_account.financialinstitution",
                    ),
                ),
            ],
            options={
                "db_table": "financial_account",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountBalanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_history",
                        to="financial_account.financialaccount",
                    ),
                ),
            ],
            options={
                "db_table": "account_balance_history",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["account", "-date"],
                        name="account_bal_account_a0b17f_idx",
                    )
                ],
                "unique_together": {("account", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="financialaccount",
            index=models.Index(fields=["user", "is_active"], name="financial_a_user_id_9d2cd7_idx"),
        ),
        migrations.AddIndex(
            model_name="financialaccount",
            index=models.Index(fields=["account_type"], name="financial_a_account_4d6451_idx"),
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="is_liability",
            field=models.BooleanField(
                default=False,
                help_text="True for credit cards and other liability accounts (excluded from net worth)",
            ),
        ),
        migrations.RunPython(
            code=set_credit_cards_as_liability,
            reverse_code=reverse_credit_cards_liability,
        ),
        migrations.RunPython(
            code=seed_institutions,
            reverse_code=reverse_seed,
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="image_key",
            field=models.CharField(
                blank=True,
                help_text="Key for custom card image. When null, auto-detect from card name.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="account_number_last4",
            field=models.CharField(
                blank=True,
                help_text="Last 4 digits of account number",
                max_length=4,
                null=True,
            ),
        ),
    ]
