# Generated by Django 4.2.24 on 2025-12-03 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("support_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "financial_institution",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Account nickname or name", max_length=255
                    ),
                ),
                (
                    "account_number_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of account number",
                        max_length=4,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking Account"),
                            ("savings", "Savings Account"),
                            ("credit_card", "Credit Card"),
                        ],
                        default="checking",
                        max_length=20,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current balance",
                        max_digits=15,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sync_source",
                    models.CharField(
                        choices=[
                            ("teller", "Teller"),
                            ("manual", "Manual Entry"),
                            ("csv", "CSV Import"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="financial_account.financialinstitution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "financial_account",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountBalanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_history",
                        to="financial_account.financialaccount",
                    ),
                ),
            ],
            options={
                "db_table": "account_balance_history",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="financialaccount",
            index=models.Index(
                fields=["user", "is_active"], name="financial_a_user_id_9d2cd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialaccount",
            index=models.Index(
                fields=["account_type"], name="financial_a_account_4d6451_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountbalancehistory",
            index=models.Index(
                fields=["account", "-date"], name="account_bal_account_a0b17f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountbalancehistory",
            unique_together={("account", "date")},
        ),
    ]
