# Generated by Django 5.1 on 2025-12-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial_account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountbalancehistory",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_history",
                to="financial_account.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="financial_account.financialinstitution",
            ),
        ),
        migrations.AddIndex(
            model_name="accountbalancehistory",
            index=models.Index(
                fields=["account", "-date"], name="account_bal_account_a0b17f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountbalancehistory",
            unique_together={("account", "date")},
        ),
        migrations.AddIndex(
            model_name="financialaccount",
            index=models.Index(
                fields=["user", "is_active"], name="financial_a_user_id_9d2cd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialaccount",
            index=models.Index(
                fields=["account_type"], name="financial_a_account_4d6451_idx"
            ),
        ),
    ]
