# Generated by Django 4.2.24 on 2025-12-05 15:43

from django.db import migrations, models


def set_credit_cards_as_liability(apps, schema_editor):
    """Set is_liability=True for existing credit card accounts."""
    FinancialAccount = apps.get_model("financial_account", "FinancialAccount")
    FinancialAccount.objects.filter(account_type="credit_card").update(
        is_liability=True
    )


def reverse_credit_cards_liability(apps, schema_editor):
    """Reverse: set is_liability=False for all accounts."""
    FinancialAccount = apps.get_model("financial_account", "FinancialAccount")
    FinancialAccount.objects.filter(account_type="credit_card").update(
        is_liability=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("financial_account", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccount",
            name="is_liability",
            field=models.BooleanField(
                default=False,
                help_text="True for credit cards and other liability accounts (excluded from net worth)",
            ),
        ),
        migrations.RunPython(
            set_credit_cards_as_liability,
            reverse_credit_cards_liability,
        ),
    ]
