# Generated by Django 4.2.24 on 2025-12-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_account", "0004_seed_financial_institutions"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccount",
            name="image_key",
            field=models.CharField(
                blank=True,
                help_text="Key for custom card image. When null, auto-detect from card name.",
                max_length=100,
                null=True,
            ),
        ),
    ]
