# Generated by Django 5.1 on 2025-12-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_account", "0005_add_image_key_to_financial_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccount",
            name="account_number_last4",
            field=models.CharField(
                blank=True,
                help_text="Last 4 digits of account number",
                max_length=4,
                null=True,
            ),
        ),
    ]
