# Generated by Django 5.1 on 2025-12-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_account", "0006_make_account_number_last4_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccount",
            name="sync_source",
            field=models.CharField(
                choices=[
                    ("plaid", "Plaid"),
                    ("manual", "Manual Entry"),
                    ("csv", "CSV Import"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
