# Generated by Cursor for local statement file organization.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_account", "0010_financialaccount_shared_with_household_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=80)),
                ("statement_period", models.CharField(blank=True, default="", max_length=40)),
                ("statement_year", models.PositiveSmallIntegerField()),
                ("statement_month", models.PositiveSmallIntegerField()),
                (
                    "statement_status",
                    models.CharField(
                        choices=[
                            ("provisional", "Current/Open Statement"),
                            ("closed", "Closed Statement"),
                        ],
                        default="provisional",
                        max_length=20,
                    ),
                ),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("previewed", "Previewed"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("stored_path", models.CharField(max_length=500)),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("file_hash", models.CharField(max_length=64)),
                ("parsed_count", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("invalid_count", models.PositiveIntegerField(default=0)),
                ("possible_changed_count", models.PositiveIntegerField(default=0)),
                ("last_import_result", models.JSONField(blank=True, default=dict)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_files",
                        to="financial_account.financialaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "statement_file",
                "ordering": ["-statement_year", "-statement_month", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_deleted"], name="statement_f_user_id_b9b45c_idx"),
                    models.Index(
                        fields=["account", "statement_year", "statement_month"],
                        name="statement_f_account_7328e7_idx",
                    ),
                    models.Index(fields=["institution"], name="statement_f_institu_16530b_idx"),
                    models.Index(fields=["file_hash"], name="statement_f_file_ha_03530c_idx"),
                    models.Index(fields=["import_status"], name="statement_f_import__97ac07_idx"),
                ],
            },
        ),
    ]
