# Generated by Django 5.1 on 2026-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_account", "0012_remove_plaid"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccount",
            name="sync_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Auto Sync via Bank Login"),
                    ("upload", "Statement Upload"),
                    ("manual", "Manual Entry"),
                ],
                default="manual",
                help_text="How this account receives transactions: auto (Playwright bank sync), upload (statement file upload), or manual (typed entries).",
                max_length=16,
            ),
        ),
    ]
