# Generated by Django 4.2.17 on 2026-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_account", "0015_google_drive_statement_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccount",
            name="storage_uri",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Drive folder URI for this account's statement files (gdrive://<folder_id>).",
                max_length=512,
            ),
        ),
    ]
