# Generated by Cursor on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_account", "0023_financialaccount_agent_activity_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbalancehistory",
            name="source",
            field=models.CharField(
                choices=[
                    ("transaction", "Transaction"),
                    ("manual", "Manual"),
                    ("csv_import", "CSV Import"),
                    ("agent_sync", "Agent Sync"),
                ],
                default="transaction",
                max_length=20,
            ),
        ),
    ]
