# Generated by Django 4.2.17 on 2026-06-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_account", "0025_remove_financialaccount_image_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialaccount",
            name="agent_activity_url_encrypted",
        ),
        migrations.RemoveField(
            model_name="financialaccount",
            name="agent_cadence",
        ),
        migrations.RemoveField(
            model_name="financialaccount",
            name="agent_sync_hour",
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="sync_mode",
            field=models.CharField(
                choices=[("upload", "Statement Upload"), ("manual", "Manual Entry")],
                default="manual",
                help_text="How this account receives transactions: upload (statement file upload) or manual (typed entries).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="statementfile",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual_upload", "Manual Upload"),
                    ("agent_drop", "Agent Drop"),
                    ("unknown", "Unknown"),
                ],
                default="manual_upload",
                help_text="How this statement entered the library: manual_upload via the UI, agent_drop via the Google Drive folder storage scanner, or unknown.",
                max_length=20,
            ),
        ),
    ]
