"""
Django settings for richtato project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from colorama import Fore
from dotenv import load_dotenv
from loguru import logger

DEPLOY_STAGE = os.getenv("DEPLOY_STAGE") or "DEV".upper()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Force DEBUG to True for local development
# DEBUG = False

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "backend",
    "frontend",
    "richtato.onrender.com",
    "richtato-dev.onrender.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://richtato.onrender.com",
]

# Application definition

INSTALLED_APPS = [
    "apps.richtato_user",
    "apps.account",
    "apps.budget",
    "apps.income",
    "apps.expense",
    "apps.settings",
    "apps.dashboard",
    "django.contrib.humanize",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "drf_yasg",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.settings.cleanup_demo_users_middleware.CleanupDemoUsersMiddleware",
]

if DEPLOY_STAGE == "PROD":
    MIDDLEWARE.insert(5, "apps.settings.self_ping_middleware.SelfPingMiddleware")


ROOT_URLCONF = "richtato.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


def log_deploy_stage_message(
    deploy_stage: str, color: str, icon: str, message: str, emoji: str
) -> None:
    logger.info(
        f"{color}{'=' * 20} {emoji} DEPLOY_STAGE: {deploy_stage.upper()} {emoji} {'=' * 20}{Fore.RESET}\n"
        f"{color}{message}{Fore.RESET}"
    )


# Function to print deploy stage in a more friendly and clear way
def print_deploy_stage(deploy_stage: str) -> None:
    match deploy_stage:
        case "LOCAL":
            log_deploy_stage_message(
                deploy_stage,
                Fore.CYAN,
                "🌟🚀",
                f">>> The current environment is {deploy_stage.upper()}! All systems go! 💻",
                "🚀",
            )

        case "DEV":
            log_deploy_stage_message(
                deploy_stage,
                Fore.GREEN,
                "🌱🎉",
                ">>> You're in development mode! Feel free to experiment! 🌟",
                "🎉",
            )

        case "PROD":
            logger.warning(
                f"{Fore.RED}{'=' * 20} 🚨🚨 WARNING: DEPLOY_STAGE is {deploy_stage.upper()} 🚨🚨 {'=' * 20}\n"
                f"{Fore.RED}>>> You are running in PRODUCTION! <<<{Fore.RESET}"
            )


# Load environment variables and set DEPLOY_STAGE
def configure_database_for_stage(deploy_stage: str) -> dict:
    match deploy_stage:
        case "LOCAL":
            return {
                "default": {
                    "ENGINE": "django.db.backends.sqlite3",
                    "NAME": BASE_DIR / "db.sqlite3",
                }
            }
        case "PROD" | "DEV":
            PG_DB_URL = f"{deploy_stage}_DATABASE_URL"
            db_url = os.getenv(PG_DB_URL)
            assert (
                db_url
            ), f"Missing {PG_DB_URL} environment variable for {deploy_stage}"
            tmpPostgres = urlparse(db_url)
            db_name = tmpPostgres.path.replace("/", "")
            return {
                "default": {
                    "ENGINE": "django.db.backends.postgresql",
                    "NAME": db_name,
                    "USER": tmpPostgres.username,
                    "PASSWORD": tmpPostgres.password,
                    "HOST": tmpPostgres.hostname,
                    "PORT": tmpPostgres.port or 5432,
                }
            }
        case _:
            raise ValueError(f"Invalid DEPLOY_STAGE: {deploy_stage}")


load_dotenv()
DATABASES = configure_database_for_stage(DEPLOY_STAGE)
print_deploy_stage(DEPLOY_STAGE)
os.environ["DEPLOY_STAGE"] = DEPLOY_STAGE


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "richtato_user.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

INTERNAL_IPS = [
    "127.0.0.1",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

# Static files collection directory for production
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration for React frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://frontend:3000",
]

CORS_ALLOW_CREDENTIALS = True

# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# Swagger Documentation Settings
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Session": {"type": "apiKey", "in": "cookie", "name": "sessionid"}
    },
    "USE_SESSION_AUTH": True,
    "JSON_EDITOR": True,
    "SUPPORTED_SUBMIT_METHODS": ["get", "post", "put", "patch", "delete"],
    "OPERATIONS_SORTER": "alpha",
    "TAGS_SORTER": "alpha",
    "DOC_EXPANSION": "list",
    "DEEP_LINKING": True,
    "SHOW_EXTENSIONS": True,
    "SHOW_COMMON_EXTENSIONS": True,
}
