"""
Django settings for richtato project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from colorama import Fore
from dotenv import load_dotenv
from loguru import logger

DEPLOY_STAGE = os.getenv("DEPLOY_STAGE") or "DEV".upper()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Force DEBUG to True for local development
# DEBUG = False

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "backend",
    "frontend",
    "richtato-latest.onrender.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://richtato-latest.onrender.com",
]

# Application definition

INSTALLED_APPS = [
    "apps.richtato_user",
    "apps.account",
    "apps.budget",
    "apps.income",
    "apps.expense",
    "apps.settings",
    "apps.dashboard",
    "django.contrib.humanize",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_yasg",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.settings.cleanup_demo_users_middleware.CleanupDemoUsersMiddleware",
]

if DEPLOY_STAGE == "PROD":
    MIDDLEWARE.insert(5, "apps.settings.self_ping_middleware.SelfPingMiddleware")


ROOT_URLCONF = "richtato.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


def log_deploy_stage_message(
    deploy_stage: str, color: str, icon: str, message: str, emoji: str
) -> None:
    logger.info(
        f"{color}{'=' * 20} {emoji} DEPLOY_STAGE: {deploy_stage.upper()} {emoji} {'=' * 20}{Fore.RESET}\n"
        f"{color}{message}{Fore.RESET}"
    )


# Function to print deploy stage in a more friendly and clear way
def print_deploy_stage(deploy_stage: str) -> None:
    match deploy_stage:
        case "LOCAL":
            log_deploy_stage_message(
                deploy_stage,
                Fore.CYAN,
                "🌟🚀",
                f">>> The current environment is {deploy_stage.upper()}! All systems go! 💻",
                "🚀",
            )

        case "DEV":
            log_deploy_stage_message(
                deploy_stage,
                Fore.GREEN,
                "🌱🎉",
                ">>> You're in development mode! Feel free to experiment! 🌟",
                "🎉",
            )

        case "PROD":
            logger.warning(
                f"{Fore.RED}{'=' * 20} 🚨🚨 WARNING: DEPLOY_STAGE is {deploy_stage.upper()} 🚨🚨 {'=' * 20}\n"
                f"{Fore.RED}>>> You are running in PRODUCTION! <<<{Fore.RESET}"
            )


# Load environment variables and set DEPLOY_STAGE
def configure_database_for_stage(deploy_stage: str) -> dict:
    """Configure Postgres for all stages (no sqlite).

    Priority:
    1. DATABASE_URL
    2. <STAGE>_DATABASE_URL (backwards-compat)
    3. Individual PG/POSTGRES_* vars with sensible local defaults
    """

    # 1) Standard DATABASE_URL if provided
    db_url = os.getenv("DATABASE_URL")

    # 2) Backwards-compatible stage-specific URL
    if not db_url:
        stage_key = f"{deploy_stage}_DATABASE_URL"
        db_url = os.getenv(stage_key)

    if db_url:
        parsed = urlparse(db_url)
        db_name = parsed.path.lstrip("/")
        # Map query params (e.g., sslmode=require) into Django OPTIONS
        query_params = {k: v[0] for k, v in parse_qs(parsed.query).items()}
        db_options: dict[str, str] = {}
        if "sslmode" in query_params:
            db_options["sslmode"] = query_params["sslmode"]
        # Allow override via env
        env_sslmode = os.getenv("DB_SSLMODE")
        if env_sslmode:
            db_options["sslmode"] = env_sslmode
        return {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": db_name,
                "USER": parsed.username,
                "PASSWORD": parsed.password,
                "HOST": parsed.hostname,
                "PORT": parsed.port or 5432,
                # Optionally: keep connections open (tune as needed)
                "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
                "OPTIONS": db_options or {},
            }
        }

    # 3) Build from individual env vars (local Postgres defaults)
    host = os.getenv("POSTGRES_HOST", "localhost")
    port = int(os.getenv("POSTGRES_PORT", "5432"))
    name = os.getenv("POSTGRES_DB", "richtato")
    user = os.getenv("POSTGRES_USER", "postgres")
    password = os.getenv("POSTGRES_PASSWORD", "")

    print(
        f"host: {host}, port: {port}, name: {name}, user: {user}, password: {password}"
    )

    return {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": name,
            "USER": user,
            "PASSWORD": password,
            "HOST": host,
            "PORT": port,
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        }
    }


load_dotenv()
DATABASES = configure_database_for_stage(DEPLOY_STAGE)
print_deploy_stage(DEPLOY_STAGE)
os.environ["DEPLOY_STAGE"] = DEPLOY_STAGE


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "richtato_user.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

INTERNAL_IPS = [
    "127.0.0.1",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

# Static files collection directory for production
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# User-uploaded media files (e.g., uploaded receipts)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration for React frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://frontend:3000",
]

CORS_ALLOW_CREDENTIALS = True

# CSRF Configuration for session authentication
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access CSRF token
CSRF_TRUSTED_ORIGINS = [
    "https://richtato-latest.onrender.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://0.0.0.0:8000",
]

# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# Swagger Documentation Settings
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Session": {"type": "apiKey", "in": "cookie", "name": "sessionid"}
    },
    "USE_SESSION_AUTH": True,
    "JSON_EDITOR": True,
    "SUPPORTED_SUBMIT_METHODS": ["get", "post", "put", "patch", "delete"],
    "OPERATIONS_SORTER": "alpha",
    "TAGS_SORTER": "alpha",
    "DOC_EXPANSION": "list",
    "DEEP_LINKING": True,
    "SHOW_EXTENSIONS": True,
    "SHOW_COMMON_EXTENSIONS": True,
}
