services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3100:3100"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend  # Connecting to backend network

volumes:
  grafana_data:  # Volume for Grafana data persistence

networks:
  backend:  # Isolated network for Django and Grafana communication