# Generated by Django 5.1 on 2026-05-23 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("financial_account", "0013_financialaccount_sync_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankLogin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User-facing label, e.g. 'Bank of America (Personal)'.",
                        max_length=120,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_login", "Pending First Login"),
                            ("active", "Active"),
                            ("needs_reauth", "Sign-in Needed"),
                            ("disabled", "Disabled"),
                            ("error", "Error"),
                        ],
                        default="pending_login",
                        max_length=24,
                    ),
                ),
                (
                    "storage_state_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fernet-encrypted Playwright storage_state JSON. Empty before first login.",
                    ),
                ),
                ("cookies_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cookies_expected_to_expire_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Best-effort estimate per institution; surfaced to the UI as 're-login needed soon'.",
                        null=True,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Only"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=16,
                    ),
                ),
                (
                    "preferred_run_hour_local",
                    models.PositiveSmallIntegerField(
                        default=6, help_text="0-23. Hour of day to run sync in the user's timezone."
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this login is next eligible for a scheduled run. NULL means manual-only.",
                        null=True,
                    ),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_failure_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_logins",
                        to="financial_account.financialinstitution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_logins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bank_login",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncedAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "flow",
                    models.CharField(
                        choices=[("deposit", "Deposit (Checking/Savings)"), ("credit_card", "Credit Card")],
                        default="deposit",
                        max_length=16,
                    ),
                ),
                (
                    "activity_url_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted activity URL including bank-specific tokens (e.g. BofA `adx`).",
                    ),
                ),
                (
                    "external_account_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank-side opaque account token. Stable across re-captures.",
                        max_length=255,
                    ),
                ),
                (
                    "detected_account_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Account name as seen on the bank site at discovery time.",
                        max_length=255,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_login",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_accounts",
                        to="bank_sync.banklogin",
                    ),
                ),
                (
                    "financial_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_account",
                        to="financial_account.financialaccount",
                    ),
                ),
            ],
            options={
                "db_table": "synced_account",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "task_kind",
                    models.CharField(
                        choices=[
                            ("interactive_login", "Interactive Login"),
                            ("scheduled_download", "Scheduled Download"),
                            ("manual_download", "Manual Download"),
                        ],
                        default="scheduled_download",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("scheduler", "Scheduler"), ("manual", "Manual"), ("user_login", "User Login Click")],
                        default="scheduler",
                        max_length=16,
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("leased_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("needs_reauth", "Needs Re-Auth"),
                            ("login_cancelled", "Login Cancelled"),
                            ("dom_broken", "DOM Broken"),
                            ("no_download", "No Download"),
                            ("import_rejected", "Import Rejected"),
                            ("config", "Configuration Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("accounts_attempted", models.PositiveIntegerField(default=0)),
                ("accounts_succeeded", models.PositiveIntegerField(default=0)),
                ("statements_imported", models.PositiveIntegerField(default=0)),
                (
                    "bank_login",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="bank_sync.banklogin"
                    ),
                ),
            ],
            options={
                "db_table": "bank_sync_run",
                "ordering": ["-queued_at"],
            },
        ),
        migrations.AddIndex(
            model_name="banklogin",
            index=models.Index(fields=["user", "status"], name="bank_login_user_id_ce2b42_idx"),
        ),
        migrations.AddIndex(
            model_name="banklogin",
            index=models.Index(fields=["next_run_at"], name="bank_login_next_ru_788abb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="banklogin",
            unique_together={("user", "institution", "nickname")},
        ),
        migrations.AddIndex(
            model_name="syncedaccount",
            index=models.Index(fields=["bank_login", "enabled"], name="synced_acco_bank_lo_39580b_idx"),
        ),
        migrations.AddIndex(
            model_name="syncrun",
            index=models.Index(fields=["bank_login", "-queued_at"], name="bank_sync_r_bank_lo_418079_idx"),
        ),
        migrations.AddIndex(
            model_name="syncrun",
            index=models.Index(fields=["status", "task_kind"], name="bank_sync_r_status_840860_idx"),
        ),
    ]
