# Generated by Django 5.1.7 on 2025-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default="1900-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
