# Generated by Django 4.2.24 on 2025-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0006_remove_expense_unique_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="details",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
