# Generated by Django 4.2.24 on 2025-10-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0007_expense_details_expense_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="receipt",
        ),
    ]
