# Generated by Django 4.2.24 on 2025-10-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0022_category_enabled"),
        ("expense", "0008_remove_expense_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="richtato_user.category",
            ),
        ),
    ]
