# Generated by Django 4.2.17 on 2026-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("richtato_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_automation_runner",
            field=models.BooleanField(
                default=False,
                help_text="Grants this account privileged access to the bank automation runner endpoints for all users.",
            ),
        ),
    ]
