# Generated by Django 5.1 on 2026-05-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("richtato_user", "0002_add_is_automation_runner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_automation_runner",
            field=models.BooleanField(
                default=False,
                help_text="Grants this account privileged access to the bank sync runner endpoints for all users.",
            ),
        ),
    ]
