# Generated by Django 4.2.18 on 2025-03-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0002_remove_user_google_sheets_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardaccount",
            name="credit_card_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bank_of_america", "Bank of America"),
                    ("chase", "Chase"),
                    ("citibank", "Citibank"),
                    ("bilt", "BILT"),
                    ("american_express", "American Express"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
