# Generated by Django 5.1.7 on 2025-04-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0005_alter_cardaccount_id_alter_category_id_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="color",
        ),
    ]
