# Generated by Cursor on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("richtato_user", "0005_userpreference_bank_agent_fernet_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="bank_sync_in_app_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show in-app notifications for bank-sync issues.",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="bank_sync_email_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Whether to send immediate email notifications for bank-sync failures.",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="bank_sync_daily_digest",
            field=models.BooleanField(
                default=True,
                help_text="Whether to include this user in scheduled bank-sync digest emails.",
            ),
        ),
    ]
