# Generated by Django 4.2.17 on 2026-06-06 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("richtato_user", "0006_bank_sync_notification_preferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreference",
            name="bank_agent_fernet_key",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="bank_sync_daily_digest",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="bank_sync_email_notifications",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="bank_sync_in_app_notifications",
        ),
    ]
