# Generated by Django 4.2.17 on 2026-06-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("richtato_user", "0007_remove_userpreference_bank_agent_fernet_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="platform_tour_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed the first-run platform tour",
            ),
        ),
    ]
