# Generated by Django 5.1.7 on 2025-04-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0012_alter_cardaccount_card_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cardaccount",
            old_name="card_type",
            new_name="card_bank",
        ),
    ]
