# Generated by Django 4.2.18 on 2025-04-20 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0013_rename_card_type_cardaccount_card_bank"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cardaccount",
            old_name="card_bank",
            new_name="bank",
        ),
    ]
