# Generated by Django 5.1.7 on 2025-06-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0016_auto_20250624_1433"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
