# Generated by Django 4.2.24 on 2025-10-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("richtato_user", "0021_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
