# Generated by Django 4.2.24 on 2025-12-03 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom Period"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "budget",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "rollover_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Roll over unspent amount to next period",
                    ),
                ),
                (
                    "rollover_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount rolled over from previous period",
                        max_digits=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_categories",
                        to="budget.budget",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_allocations",
                        to="transaction.transactioncategory",
                    ),
                ),
            ],
            options={
                "db_table": "budget_category",
                "ordering": ["category__name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("transaction_count", models.IntegerField(default=0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "budget_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="budget.budgetcategory",
                    ),
                ),
            ],
            options={
                "db_table": "budget_progress",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["budget_category", "-period_start"],
                        name="budget_prog_budget__541c6a_idx",
                    ),
                    models.Index(
                        fields=["-last_calculated"],
                        name="budget_prog_last_ca_f143d9_idx",
                    ),
                ],
                "unique_together": {("budget_category", "period_start", "period_end")},
            },
        ),
        migrations.AddIndex(
            model_name="budgetcategory",
            index=models.Index(
                fields=["budget", "category"], name="budget_cate_budget__388195_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetcategory",
            unique_together={("budget", "category")},
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "is_active"], name="budget_user_id_dfe767_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["start_date", "end_date"], name="budget_start_d_42c9ae_idx"
            ),
        ),
    ]
