# Generated by Django 5.1 on 2025-12-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom Period"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "budget",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "rollover_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Roll over unspent amount to next period",
                    ),
                ),
                (
                    "rollover_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount rolled over from previous period",
                        max_digits=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "budget_category",
                "ordering": ["category__name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("transaction_count", models.IntegerField(default=0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "budget_progress",
                "ordering": ["-period_start"],
            },
        ),
    ]
