# Generated by Django 5.1 on 2025-12-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget", "0001_initial"),
        ("transaction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetcategory",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_categories",
                to="budget.budget",
            ),
        ),
        migrations.AddField(
            model_name="budgetcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_allocations",
                to="transaction.transactioncategory",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogress",
            name="budget_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_records",
                to="budget.budgetcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "is_active"], name="budget_user_id_9a79b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["start_date", "end_date"], name="budget_start_d_b5ffbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetcategory",
            index=models.Index(
                fields=["budget", "category"], name="budget_cate_budget__388195_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetcategory",
            unique_together={("budget", "category")},
        ),
        migrations.AddIndex(
            model_name="budgetprogress",
            index=models.Index(
                fields=["budget_category", "-period_start"],
                name="budget_prog_budget__541c6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetprogress",
            index=models.Index(
                fields=["-last_calculated"], name="budget_prog_last_ca_f143d9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetprogress",
            unique_together={("budget_category", "period_start", "period_end")},
        ),
    ]
