# Generated by Django 4.2.29 on 2026-04-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="is_household",
            field=models.BooleanField(
                default=False, help_text="Whether this is a household-level budget visible in household scope."
            ),
        ),
    ]
