# Generated by Django 5.1 on 2025-12-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategorizationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ai", "AI Categorization"),
                            ("rule", "Rule-based"),
                            ("manual", "Manual"),
                            ("suggestion", "AI Suggestion (not applied)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score for AI categorization (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "categorization_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategorizationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_ids",
                    models.JSONField(help_text="List of transaction IDs to categorize"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("batch_size", models.IntegerField(default=75)),
                ("transactions_processed", models.IntegerField(default=0)),
                ("transactions_categorized", models.IntegerField(default=0)),
                ("transactions_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "categorization_queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategorizationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority rules are checked first"
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("merchant", "Merchant Name"),
                            ("description_contains", "Description Contains"),
                            ("description_exact", "Description Exact Match"),
                            ("amount_range", "Amount Range"),
                            ("amount_exact", "Amount Exact"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        help_text="The value to match against", max_length=500
                    ),
                ),
                (
                    "condition_value_max",
                    models.CharField(
                        blank=True,
                        help_text="For range conditions (e.g., amount_range)",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "categorization_rule",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCategorizationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_pattern",
                    models.CharField(
                        help_text="Pattern from transaction description", max_length=500
                    ),
                ),
                (
                    "use_count",
                    models.IntegerField(
                        default=1,
                        help_text="How many times user chose this category for this pattern",
                    ),
                ),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_categorization_preference",
                "ordering": ["-use_count", "-last_used"],
            },
        ),
    ]
