# Generated by Django 4.2.24 on 2025-12-03 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorizationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority rules are checked first"
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("merchant", "Merchant Name"),
                            ("description_contains", "Description Contains"),
                            ("description_exact", "Description Exact Match"),
                            ("amount_range", "Amount Range"),
                            ("amount_exact", "Amount Exact"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        help_text="The value to match against", max_length=500
                    ),
                ),
                (
                    "condition_value_max",
                    models.CharField(
                        blank=True,
                        help_text="For range conditions (e.g., amount_range)",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_rules",
                        to="transaction.transactioncategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "categorization_rule",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategorizationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ai", "AI Categorization"),
                            ("rule", "Rule-based"),
                            ("manual", "Manual"),
                            ("suggestion", "AI Suggestion (not applied)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score for AI categorization (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_history",
                        to="transaction.transactioncategory",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="The rule that triggered this categorization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categorization_history",
                        to="categorization.categorizationrule",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_history",
                        to="transaction.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "categorization_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCategorizationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_pattern",
                    models.CharField(
                        help_text="Pattern from transaction description", max_length=500
                    ),
                ),
                (
                    "use_count",
                    models.IntegerField(
                        default=1,
                        help_text="How many times user chose this category for this pattern",
                    ),
                ),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_preferences",
                        to="transaction.merchant",
                    ),
                ),
                (
                    "preferred_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_preferences",
                        to="transaction.transactioncategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_categorization_preference",
                "ordering": ["-use_count", "-last_used"],
                "indexes": [
                    models.Index(
                        fields=["user", "merchant"],
                        name="user_catego_user_id_ade643_idx",
                    ),
                    models.Index(
                        fields=["user", "description_pattern"],
                        name="user_catego_user_id_25255d_idx",
                    ),
                    models.Index(
                        fields=["-use_count"], name="user_catego_use_cou_10acd9_idx"
                    ),
                ],
                "unique_together": {("user", "description_pattern", "merchant")},
            },
        ),
        migrations.AddIndex(
            model_name="categorizationrule",
            index=models.Index(
                fields=["user", "is_active", "-priority"],
                name="categorizat_user_id_59aaf7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationrule",
            index=models.Index(
                fields=["condition_type"], name="categorizat_conditi_7e28a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationhistory",
            index=models.Index(
                fields=["transaction"], name="categorizat_transac_324314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationhistory",
            index=models.Index(fields=["method"], name="categorizat_method_60bf47_idx"),
        ),
        migrations.AddIndex(
            model_name="categorizationhistory",
            index=models.Index(
                fields=["-created_at"], name="categorizat_created_bb47e3_idx"
            ),
        ),
    ]
