# Generated by Django 5.1 on 2025-12-25 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorizationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_ids",
                    models.JSONField(help_text="List of transaction IDs to categorize"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("batch_size", models.IntegerField(default=75)),
                ("transactions_processed", models.IntegerField(default=0)),
                ("transactions_categorized", models.IntegerField(default=0)),
                ("transactions_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "categorization_queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategorizationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ai", "AI Categorization"),
                            ("keyword", "Keyword-based"),
                            ("manual", "Manual"),
                            ("suggestion", "AI Suggestion (not applied)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score for AI categorization (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_history",
                        to="transaction.transactioncategory",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_history",
                        to="transaction.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "categorization_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
