# Generated by Django 4.2.24 on 2025-12-03 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categorization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorizationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_ids",
                    models.JSONField(help_text="List of transaction IDs to categorize"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("batch_size", models.IntegerField(default=75)),
                ("transactions_processed", models.IntegerField(default=0)),
                ("transactions_categorized", models.IntegerField(default=0)),
                ("transactions_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization_queues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "categorization_queue",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="categorizat_user_id_65364b_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="categorizat_status_9f1405_idx",
                    ),
                ],
            },
        ),
    ]
