# Generated by Django 5.1 on 2025-12-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categorization", "0001_initial"),
        ("transaction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="categorizationhistory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorization_history",
                to="transaction.transactioncategory",
            ),
        ),
        migrations.AddField(
            model_name="categorizationhistory",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorization_history",
                to="transaction.transaction",
            ),
        ),
        migrations.AddField(
            model_name="categorizationqueue",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorization_queues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="categorizationrule",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorization_rules",
                to="transaction.transactioncategory",
            ),
        ),
        migrations.AddField(
            model_name="categorizationrule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorization_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="categorizationhistory",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                help_text="The rule that triggered this categorization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categorization_history",
                to="categorization.categorizationrule",
            ),
        ),
        migrations.AddField(
            model_name="usercategorizationpreference",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorization_preferences",
                to="transaction.merchant",
            ),
        ),
        migrations.AddField(
            model_name="usercategorizationpreference",
            name="preferred_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorization_preferences",
                to="transaction.transactioncategory",
            ),
        ),
        migrations.AddField(
            model_name="usercategorizationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorization_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationqueue",
            index=models.Index(
                fields=["user", "status"], name="categorizat_user_id_65364b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationqueue",
            index=models.Index(
                fields=["status", "-created_at"], name="categorizat_status_9f1405_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationrule",
            index=models.Index(
                fields=["user", "is_active", "-priority"],
                name="categorizat_user_id_59aaf7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationrule",
            index=models.Index(
                fields=["condition_type"], name="categorizat_conditi_7e28a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationhistory",
            index=models.Index(
                fields=["transaction"], name="categorizat_transac_324314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationhistory",
            index=models.Index(fields=["method"], name="categorizat_method_60bf47_idx"),
        ),
        migrations.AddIndex(
            model_name="categorizationhistory",
            index=models.Index(
                fields=["-created_at"], name="categorizat_created_bb47e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercategorizationpreference",
            index=models.Index(
                fields=["user", "merchant"], name="user_catego_user_id_ade643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercategorizationpreference",
            index=models.Index(
                fields=["user", "description_pattern"],
                name="user_catego_user_id_25255d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usercategorizationpreference",
            index=models.Index(
                fields=["-use_count"], name="user_catego_use_cou_10acd9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercategorizationpreference",
            unique_together={("user", "description_pattern", "merchant")},
        ),
    ]
