# Generated by Django 5.1 on 2025-12-25 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categorization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="categorizationqueue",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorization_queues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationhistory",
            index=models.Index(
                fields=["transaction"], name="categorizat_transac_324314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationhistory",
            index=models.Index(fields=["method"], name="categorizat_method_60bf47_idx"),
        ),
        migrations.AddIndex(
            model_name="categorizationhistory",
            index=models.Index(
                fields=["-created_at"], name="categorizat_created_bb47e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationqueue",
            index=models.Index(
                fields=["user", "status"], name="categorizat_user_id_65364b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorizationqueue",
            index=models.Index(
                fields=["status", "-created_at"], name="categorizat_status_9f1405_idx"
            ),
        ),
    ]
