# Generated by Django 5.1 on 2025-12-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorization", "0003_remove_deprecated_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorizationhistory",
            name="method",
            field=models.CharField(
                choices=[
                    ("ai", "AI Categorization"),
                    ("keyword", "Keyword-based"),
                    ("manual", "Manual"),
                    ("suggestion", "AI Suggestion (not applied)"),
                ],
                max_length=20,
            ),
        ),
    ]
